package com.qf.entity;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.id
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.per_name
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    private String perName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.per_url
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    private String perUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.per_code
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    private String perCode;

    private Integer isParent;

    private String perPname;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.per_pid
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    private Integer perPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.per_type
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    private Integer perType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.id
     *
     * @return the value of t_permission.id
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.id
     *
     * @param id the value for t_permission.id
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.per_name
     *
     * @return the value of t_permission.per_name
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.per_name
     *
     * @param perName the value for t_permission.per_name
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.per_url
     *
     * @return the value of t_permission.per_url
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public String getPerUrl() {
        return perUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.per_url
     *
     * @param perUrl the value for t_permission.per_url
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public void setPerUrl(String perUrl) {
        this.perUrl = perUrl == null ? null : perUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.per_code
     *
     * @return the value of t_permission.per_code
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public String getPerCode() {
        return perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.per_code
     *
     * @param perCode the value for t_permission.per_code
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public void setPerCode(String perCode) {
        this.perCode = perCode == null ? null : perCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.per_pid
     *
     * @return the value of t_permission.per_pid
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public Integer getPerPid() {
        return perPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.per_pid
     *
     * @param perPid the value for t_permission.per_pid
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public void setPerPid(Integer perPid) {
        this.perPid = perPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.per_type
     *
     * @return the value of t_permission.per_type
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public Integer getPerType() {
        return perType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.per_type
     *
     * @param perType the value for t_permission.per_type
     *
     * @mbggenerated Tue Aug 04 10:18:10 CST 2020
     */
    public void setPerType(Integer perType) {
        this.perType = perType;
    }

    public Integer getIsParent() {
        return isParent;
    }

    public void setIsParent(Integer isParent) {
        this.isParent = isParent;
    }

    public String getPerPname() {
        return perPname;
    }

    public void setPerPname(String perPname) {
        this.perPname = perPname;
    }
}